name: Chrome

on:
  push:
    branches:
      - Developerstory39

jobs:
  selenium_test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        browser: [chrome]
        python-version: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt

      - name: execute py script 
        run: |
          python test_01_register.py