
name: Selenium

on:
  push:
    branches: [ Developerstory39 ]

jobs:
  selenium_test_ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt

      - name: start flask application
        run: |
          python main.py &
          sleep 2s

      - name: init db  
        run: |
          flask mockdata init-mockdata

      - name: execute test scripts 
        run: |
          echo testing registration
          python tests_selenium/test_01_register.py
          echo testing login
          python tests_selenium/test_02_login.py
          

  selenium_test_windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt

      - name: start flask application, init db and start testing
        run: |
          start-job -scriptblock{python.exe "D:\a\Anwendungsprojekt\Anwendungsprojekt\main.py"}
          start-sleep -Seconds 2
          flask mockdata init-mockdata
          start-sleep -Seconds 2
          write-host("testing registration")
          python tests_selenium/test_01_register.py
          write-host("testing login")
          python tests_selenium/test_02_login.py 

  selenium_test_macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@latest
      - run: chromium --version

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt

      - name: start flask application
        run: |
          python main.py &
          sleep 10s

      - name: init db
        run: |
          flask mockdata init-mockdata

      - name: execute test scripts
        run: |
          echo testing registration
          python tests_selenium/test_01_register.py
          echo testing login
          python tests_selenium/test_02_login.py